# Generated by Django 2.1.4 on 2018-12-25 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img_db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='img',
            old_name='img_url',
            new_name='img',
        ),
    ]
